### DISCUSSION TITLE
Sonoff Dongle-P firmware not working when joining device

### DISCUSSION THREAD

**Discussion by Caros2017** [Koenkk/OpenThread-TexasInstruments-firmware#4] [General]
Hi,

I am using the SONOFF ZBDongle-P. I flashed this with this command:
`python.exe .\cc2538_bsl.py --bootloader-sonoff-usb -e -w -v -p COM3 .\CC1352P2_CC2652P_launchpad_ot_rcp_2025_3_1.hex`

For the test I have also tried the `other` firmware but it gave the same result.

I use the otbr docker-container. Relevant docker-compose values:
```
    image: openthread/otbr:latest
    container_name: openthreadbr
    privileged: true
    volumes:
      - ./data:/var/lib/thread
    devices:
      - /dev/ttyUSB1:/dev/ttyUSB1 # Sonoff Dongle
    environment:
      - BACKBONE_INTERFACE=eth0 
      - FIREWALL=0
      - FLOW_CONTROL=0
      - AUTOFLASH_FIRMWARE=0 
      - OTBR_ENABLE=1
      - OTBR_LOG_LEVEL=info
      - OTBR_REST_PORT=8081
      - OTBR_REST_LISTEN_PORT=8081
      - OTBR_WEB_PORT=8080
      - RADIO_URL=spinel+hdlc+uart:///dev/ttyUSB1?uart-baudrate=460800
```
So far so good. In Home assistant I have added my border router and it all seems fine. In the webinterface of otbr I see my OTBR border router. And also the logs of the docker container seem fine at this stage.

But then I want to join a device. In this case I have one device, the Aqara U200 Lite lock. When joining this to home assistant it goes to all stages, but crashes at joining network: `Checking network connectivity to "SSID"

Tshooting gives me the following:
- The Border router dissapears in homeassistant
- The OTBR daemon crashes totally:
```
[W] P-RadioSpinel-: Wait for response timeout
[C] P-RadioSpinel-: Failed to communicate with RCP - no response from RCP during initialization
[C] P-RadioSpinel-: This is not a bug and typically due a config error (wrong URL parameters) or bad RCP image:
[C] P-RadioSpinel-: - Make sure RCP is running the correct firmware
[C] P-RadioSpinel-: - Double check the config parameters passed as `RadioURL` input
[C] Platform------: HandleRcpTimeout() at radio_spinel.cpp:2035: RadioSpinelNoResponse
```

I have tried a lot, but I don't know what to do next. I reflashed the firmware multiple times. It seems like the dongle is overloaded with messages or something and then totally crashes. Any ideas how to solve this? Everything I try seems to give the same result.
